###############################################################
# MODULE: KeyVaultSecrets - Variables
###############################################################

variable "key_vault_id" {
  type        = string
  description = "Key Vault resource ID to push secrets to."
  nullable    = false

  validation {
    condition     = can(regex("^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\\.KeyVault/vaults/[^/]+$", var.key_vault_id))
    error_message = "key_vault_id must be a valid Azure Key Vault resource ID."
  }
}

variable "secrets" {
  description = <<-EOT
  Map of secrets to create in the Key Vault.
  Either `value` OR `generate` must be set (mutually exclusive).

  - `name`            - (Required) Secret name.
  - `value`           - (Optional) Explicit secret value.
  - `generate`        - (Optional) If set, random password generated by the module:
    - `length`         - (Optional) Password length. Defaults to 32.
    - `special`        - (Optional) Include special chars. Defaults to true.
    - `override_special` - (Optional) Restrict special chars to this set.
  - `content_type`    - (Optional) Metadata describing the secret (e.g. "password", "key").
  - `expiration_date` - (Optional) ISO 8601 expiration timestamp (e.g. "2027-01-01T00:00:00Z").
  - `tags`            - (Optional) Tags on the secret.
  EOT
  type = map(object({
    name  = string
    value = optional(string)
    generate = optional(object({
      length           = optional(number, 32)
      special          = optional(bool, true)
      override_special = optional(string)
    }))
    content_type    = optional(string)
    expiration_date = optional(string)
    tags            = optional(map(string), {})
  }))
  nullable = false

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      (v.value != null) != (v.generate != null) # exactly one must be set
    ])
    error_message = "Each secret must have exactly one of `value` or `generate` set."
  }
}
